# Use Node.js v22.15.0
FROM node:22.15.0

# Create app directory
WORKDIR /usr/src/app

# Copy package.json and package-lock.json
COPY package*.json ./

# Clean up existing node_modules (in case there are leftovers from previous builds)
RUN rm -rf node_modules

# Check if package-lock.json exists and install dependencies
RUN if [ -f package-lock.json ]; then npm ci; else npm install; fi

# Copy the rest of the application files
COPY . .

# Expose the port your app will run on
EXPOSE 8080

# Start the application
CMD [ "npm", "run", "prod" ]

