apiVersion: v1
kind: Service
metadata:
  name: publicreverseproxy
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"  # Correct type
spec:
  type: LoadBalancer
  selector:
    app: reverseproxy
  ports:
    - port: 80
      targetPort: 8080
