apiVersion: v1
kind: Service
metadata:
  name: udagram-frontend
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"  # Correct type
spec:
  type: LoadBalancer  # Expose externally through AWS Load Balancer
  ports:
    - port: 80          # Publicly accessible port
      targetPort: 80    # Internal container port your frontend listens on
  selector:
    app: udagram-frontend  # Ensure this matches your frontend pod/deployment labels

