apiVersion: v1
kind: Service
metadata:
  name: udagram-api-user
spec:
  type: ClusterIP
  selector:
    app: udagram-api-user
  ports:
    - port: 8080         # Exposed to NGINX and other services
      targetPort: 8080   # Actual app port inside the container

